INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AA name', '1', 'Question AA explanation', b'0', 'Question AA details', 'Question AA type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AB name', '1', 'Question AB explanation', b'0', 'Question AB details', 'Question AB type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AC name', '1', 'Question AC explanation', b'0', 'Question AC details', 'Question AC type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AD name', '1', 'Question AD explanation', b'0', 'Question AD details', 'Question AD type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AE name', '1', 'Question AE explanation', b'0', 'Question AE details', 'Question AE type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AF name', '1', 'Question AF explanation', b'0', 'Question AF details', 'Question AF type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AG name', '1', 'Question AG explanation', b'0', 'Question AG details', 'Question AG type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AH name', '1', 'Question AH explanation', b'0', 'Question AH details', 'Question AH type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AI name', '1', 'Question AI explanation', b'0', 'Question AI details', 'Question AI type', '1', '1');
INSERT INTO `question` (`id`, `creation_date_time`, `for_exam`, `is_enabled`, `name`, `programming_language`, `explanation_answer`, `is_obsolete`, `question`, `type_of_question`, `creator_id`, `correct_answers_id`) VALUES (NULL, '2016-12-15 9:15:32', '1', b'1', 'Question AJ name', '1', 'Question AJ explanation', b'0', 'Question AJ details', 'Question AJ type', '1', '1');

INSERT INTO `question_possible_answers` (`question_id`, `possible_answers`) VALUES ('1', 'Yes, it is correct'), ('1', 'No, a*a cannot be within a for loop');
INSERT INTO `question_possible_answers` (`question_id`, `possible_answers`) VALUES ('2', 'Yes, it is correct'), ('2', 'No, a*a cannot be within a for loop'), ('2', 'No, the break is not allowed in the if statement');

